name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install --ignore-scripts

      - name: Run lint
        run: npm run lint
